apiVersion: apps/v1
kind: Deployment
metadata:
  name: musta-deployment
  labels:
    app: musta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musta
  template:
    metadata:
      labels:
        app: musta
    spec:
      containers:
      - name: musta-container
        image: adil5800/musta:v1
        ports:
        - containerPort: 80
        
---
 apiVersion: v1
 kind: Service
 metadata:
   name: running-service
 spec:
   type: ClusterIP
   selector:
     app: running
   ports:
   - port: 80
     targetPort: 80